CatFlowers/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from core.views import *
from allauth.account.views import LoginView, SignupView, LogoutView

app_name = 'core'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order_summary/', OrderSummaryView.as_view(), name='order_summary'),
    path('add_to_cart/<slug>/', add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<slug>/', remove_from_cart, name='remove_from_cart'),
    path('remove_single_item_from_cart/<slug>/',
         remove_single_item_from_cart, name='remove_single_item_from_cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('add_coupon/', AddCouponView.as_view(), name='add_coupon'),
    path('request_refund/', RequestRefundView.as_view(), name='request_refund'),



    path('accounts/login/', LoginView.as_view(), name='account_login'),
    path('accounts/logout/', LogoutView.as_view(), name='account_logout'),
    path('accounts/signup/', SignupView.as_view(), name='account_signup'),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

from django.conf import settings
from django.shortcuts import reverse, get_object_or_404
from django.db.models import Sum
from django_countries.fields import CountryField

# Create your models here.
CATEGORY_CHOICES = (
    ('S', 'NAM'),
    ('SW', 'NỮ'),
    ('OW', 'TRẺ EM'),
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger'),
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)


class Item(models.Model):
    title = models.CharField(max_length=100)  # TieuDe
    price = models.IntegerField()  # gia ban san pham
    discount_price = models.IntegerField(
        blank=True, null=True)  # giam gia ban san pham
    category = models.CharField(
        choices=CATEGORY_CHOICES, max_length=2)  # the loai
    # nhan(new / bestseller ...)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()  # mieu ta
    image = models.ImageField(blank=True, null=True)
    image2 = models.ImageField(blank=True, null=True)
    image3 = models.ImageField(blank=True, null=True)
    image4 = models.ImageField(blank=True, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            "slug": self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add_to_cart", kwargs={
            "slug": self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove_from_cart", kwargs={
            "slug": self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE, blank=True, null=True)
    ordered = models.BooleanField(default=False)
    # la khoa chinh cua bang Item
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)  # so luong

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE, blank=True, null=True)  # user la khoa chinh cua Auth
    ref_code = models.CharField(max_length=30, blank=True, null=True)
    # qhe nhieu nhieu thong qua bang OrderItem
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)  # ngay bat dau
    ordered_date = models.DateTimeField()  # ngay dat hang
    ordered = models.BooleanField(default=False)  # dat hang hay chua dat hang
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        'Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)  # Dang giao hang
    received = models.BooleanField(default=False)  # Da nhan hang
    refund_requested = models.BooleanField(default=False)  # yeu cau hoan tien
    refund_granted = models.BooleanField(default=False)  # hoan lai tien

    """
    1. Item added to cart
    2. Adding a billing address
    (Failed checkout)
    3. Payment
    (Preprocessing, processing, packaging etc.)
    4. Being delivered
    5. Received
    6. Refunds

    """

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE, blank=True, null=True)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    # phone = models.CharField(max_length=100)
    zipcode = models.CharField(max_length=100, blank=True, null=True)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.IntegerField(blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()  # li do
    accepted = models.BooleanField(default=False)  # da dong y
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"

templates/base.html
{% load cart_template_tags %} {% load static %} {% load i18n %} {% load account socialaccount %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %} {% endblock %}
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    <!-- Material Design Bootstrap -->
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet" type="text/css">
    <!-- Your custom styles (optional) -->
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet" type="text/css">
    <style type="text/css">
        html,
        body,
        header,
        .carousel {
            height: 60vh;
        }
        
        @media (max-width: 740px) {
            html,
            body,
            header,
            .carousel {
                height: 100vh;
            }
        }
        
        @media (min-width: 800px) and (max-width: 850px) {
            html,
            body,
            header,
            .carousel {
                height: 100vh;
            }
        }
    </style>
</head>


<body>
    <!-- Navbar -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
        <div class="container">

            <!-- Brand -->
            <a class="navbar-brand waves-effect" href="{% url 'core:home' %}" target="_blank">
                <strong class="blue-text badge grey z-depth-1 mr-1" style="font-size: 100%;">Cat Flowers</strong>
            </a>

            <!-- Collapse -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

            <!-- Links -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <!-- Left -->
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link waves-effect" href="{% url 'core:home' %}">Trang Chủ
              <span class="sr-only">(current)</span>
            </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link waves-effect" href="{% url 'core:checkout' %}" target="_blank">Thanh Toán</a>
                    </li>
                </ul>

                <!-- Right -->
                <ul class="navbar-nav nav-flex-icons">
                    {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a href="#" class="nav-link waves-effect">
                            <span class="badge green z-depth-1 mr-1">Xin chào,{{ request.user.username }}</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'core:order_summary' %}" class="nav-link waves-effect">
                            <span class="badge red z-depth-1 mr-1">{{ request.user|cart_item_count }}</span>
                            <i class="fas fa-shopping-cart"></i>
                            <span class="clearfix d-none d-sm-inline-block"> Giỏ Hàng </span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link waves-effect" href="{% url 'core:account_logout' %}">
                            <span class="clearfix d-none d-sm-inline-block"> Đăng Xuất </span>
                        </a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link waves-effect" href="{% url 'core:account_login' %}">
                            <span class="clearfix d-none d-sm-inline-block"> Đăng Nhập </span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link waves-effect" href="{% url 'core:account_signup' %}">
                            <span class="clearfix d-none d-sm-inline-block"> Đăng Ký </span>
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <!-- Navbar -->
    <div class="mt-5 pt-4">
        {% if messages %} {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %} {% endif %}
    </div>

    {% block content %} {% endblock content %} {% block extra_body %} {% endblock %}
    <!--Footer-->
    <footer class="page-footer text-center font-small mt-4 wow fadeIn">

        <!-- Social icons -->
        <div class="pb-4">
            <a href="https://www.facebook.com/mdbootstrap" target="_blank">
                <i class="fab fa-facebook-f mr-3"></i>
            </a>

            <a href="https://twitter.com/MDBootstrap" target="_blank">
                <i class="fab fa-twitter mr-3"></i>
            </a>

            <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
                <i class="fab fa-youtube mr-3"></i>
            </a>

            <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
                <i class="fab fa-google-plus-g mr-3"></i>
            </a>

            <a href="https://dribbble.com/mdbootstrap" target="_blank">
                <i class="fab fa-dribbble mr-3"></i>
            </a>

            <a href="https://pinterest.com/mdbootstrap" target="_blank">
                <i class="fab fa-pinterest mr-3"></i>
            </a>

            <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
                <i class="fab fa-github mr-3"></i>
            </a>

            <a href="http://codepen.io/mdbootstrap/" target="_blank">
                <i class="fab fa-codepen mr-3"></i>
            </a>
        </div>
        <!-- Social icons -->

        <!--Copyright-->
        <div class="footer-copyright py-3">
            © 2020 Copyright:
            <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> CatFlowers.com </a>
        </div>
        <!--/.Copyright-->

    </footer>
    <!--/.Footer-->

    <!-- SCRIPTS -->
    <!-- JQuery -->
    <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
    <!-- Initializations -->
    <script type="text/javascript">
        // Animations initialization
        new WOW().init();
    </script>

    {% block extra_scripts %} {% endblock extra_scripts %}
</body>

</html>

templates/home.html
{% extends "base.html" %} {% load humanize %} {% load static %} {% block content %}
<!--Carousel Wrapper-->
<div id="carousel-example-1z" class="carousel slide carousel-fade pt-4" data-ride="carousel">
    <!--Indicators-->
    <ol class="carousel-indicators">
        <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-1z" data-slide-to="1"></li>
        <li data-target="#carousel-example-1z" data-slide-to="2"></li>
    </ol>
    <!--/.Indicators-->
    <!--Slides-->
    <div class="carousel-inner" role="listbox">
        <!--First slide-->
        <div class="carousel-item active">
            <div class="view" style="background-image: url('/static/img/detail/bg1.png'); background-repeat: no-repeat; background-size: cover;">
            </div>
        </div>
        <!--/First slide-->
        <!--Second slide-->
        <div class="carousel-item">
            <div class="view" style="background-image: url('/static/img/detail/bg2.png'); background-repeat: no-repeat; background-size: cover;">
            </div>
        </div>
        <!--/Second slide-->
        <!--Third slide-->
        <div class="carousel-item">
            <div class="view" style="background-image: url('/static/img/detail/bg5.png'); background-repeat: no-repeat; background-size: cover;">
            </div>
        </div>
        <!--/Third slide-->
    </div>
    <!--/.Slides-->

    <!--Controls-->
    <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
    <!--/.Controls-->

</div>
<!--/.Carousel Wrapper-->

<!--Main layout-->
<main>
    <div class="container">

        <!--Navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

            <!-- Navbar brand -->
            <span class="navbar-brand">Danh mục:</span>

            <!-- Collapse button -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav" aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

            <!-- Collapsible content -->
            <div class="collapse navbar-collapse" id="basicExampleNav">

                <!-- Links -->
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Tất cả
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Nam</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Nữ</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Trẻ Em</a>
                    </li>
                </ul>
                <!-- Links -->

                <form class="form-inline">
                    <div class="md-form my-0">
                        <input class="form-control mr-sm-2" type="text" placeholder="Tìm kiếm" aria-label="Search">
                    </div>
                </form>
            </div>
            <!-- Collapsible content -->

        </nav>
        <!--/.Navbar-->

        <!--Section: Products v.3-->
        <section class="text-center mb-4">

            <!--Grid row-->
            <div class="row wow fadeIn">

                <!--Grid column-->
                {% for item in object_list %}
                <div class="col-lg-3 col-md-6 mb-4">

                    <!--Card-->
                    <div class="card">

                        <!--Card image-->
                        <div class="view overlay">
                            <!-- <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top" alt=""> -->
                            <img src="{{ item.image.url }}" class="card-img-top">
                            <a href="{{ item.get_absolute_url }}">
                                <div class="mask rgba-white-slight"></div>
                            </a>
                        </div>
                        <!--Card image-->

                        <!--Card content-->
                        <div class="card-body text-center">
                            <!--Category & Title-->
                            <a href="" class="grey-text">
                                <h5>{{ item.get_category_display }}</h5>
                            </a>
                            <h5>
                                <strong>
                <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{item.title}}
                    <span class="badge badge-pill {{ item.get_label_display }}-color">Mới</span>
                </a>
                </strong>
                            </h5>

                            <h4 class="font-weight-bold blue-text">
                                <strong>
                                    {% if item.discount_price %}
                                        {{ item.discount_price|intcomma }}
                                    {% else %}
                                        {{ item.price|intcomma }} 
                                    {% endif %}
                                    đ
                                </strong>
                            </h4>

                        </div>
                        <!--Card content-->

                    </div>
                    <!--Card-->

                </div>
                {% endfor %}

                <!--Grid column-->

            </div>
            <!--Grid row-->


        </section>
        <!--Section: Products v.3-->

        <!--Pagination-->
        {% if is_paginated %}
        <nav class="d-flex justify-content-center wow fadeIn">
            <ul class="pagination pg-blue">

                <!--control page-->
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Previous</span>
                    </a>
                </li>
                {% endif %}
                <li class="page-item active">
                    <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
                        <span class="sr-only">(current)</span>
                    </a>
                </li>

                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Next</span>
                    </a>
                </li>
                {% endif %}
            </ul>
        </nav>

        {% endif %}
        <!--Pagination-->

    </div>
</main>
<!--Main layout-->
{% endblock content %}

templates/item_list.html
{% extends "base.html" %}

{% block content  %}
<h2>
    Here is the list of items
</h2>
{% for item in items  %}
{{ item }}
{{ item.price }}
{% endfor %}
{% endblock content %}

templates/order_snippet.html
{% load humanize %}
<div class="col-md-12 mb-4">

    <!-- Heading -->
    <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">Giỏ hàng của bạn:</span>
        <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>

    <!-- Cart -->
    <ul class="list-group mb-3 z-depth-1">
        {% for order_item in order.items.all %}
        <li class="list-group-item d-flex justify-content-between lh-condensed">
            <div>
                <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title }}</h6>
                <small class="text-muted">{{ order_item.item.description }}</small>
            </div>
            <span class="text-muted">{{ order_item.get_final_price|intcomma }} đ</span>
        </li>
        {% endfor %} {% if order.coupon %}
        <li class="list-group-item d-flex justify-content-between bg-light">
            <div class="text-success">
                <h6 class="my-0">Mã Khuyến Mại:</h6>
                <small>{{ order.coupon.code }}</small>
            </div>
            <span class="text-success">-{{ order.coupon.amount|intcomma }} đ</span>
        </li>
        {% endif %}
        <li class="list-group-item d-flex justify-content-between">
            <span>Tổng tiền (VND)</span>
            <strong>{{ order.get_total|intcomma }} đ</strong>
        </li>
    </ul>
    <!-- Cart -->
    <!-- Promo code -->
    {% if DISPLAY_COUPON_FORM %}
    <form class="card p-2" action="{% url 'core:add_coupon' %}" method="POST">
        {% csrf_token %}
        <div class="input-group">
            <!-- <input type="text" class="form-control" placeholder="Promo code" aria-label="Recipient's username" aria-describedby="basic-addon2"> -->
            {{ couponform.code }}
            <div class="input-group-append">
                <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Nhập Mã</button>
            </div>
        </div>
    </form>
    {% endif %}
    <!-- Promo code -->
</div>

templates/order_summary.html
{% extends "base.html" %} {% load humanize %} {% load static %} {% block content %}
<!--Main layout-->
<main>
    <div class="container">

        <div class="table-responsive text-nowrap">
            <h2>GIỎ HÀNG CỦA BẠN:</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">STT</th>
                        <th scope="col">Tên sản phẩm</th>
                        <th scope="col">Bảng giá</th>
                        <th scope="col">Số lượng</th>
                        <th scope="col">Tổng tiền</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order_item in object.items.all %}
                    <tr>
                        <!--forloop.counter : dem so thu tu-->
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ order_item.item.title}}</td>
                        <td>{{ order_item.item.price|intcomma}} đ</td>
                        <td>
                            <a href="{% url 'core:add_to_cart' order_item.item.slug %}"><i class="fas fa-plus mr-2"></i></a> {{ order_item.quantity}}
                            <a href="{% url 'core:remove_single_item_from_cart' order_item.item.slug %}"><i class="fas fa-minus ml-2"></i></a>
                        </td>
                        <td>
                            {% if order_item.item.discount_price %} {{ order_item.get_total_discount_item_price|intcomma }} đ
                            <span class="badge badge-success">Đã giám giá: {{ order_item.get_amount_saved|intcomma }} đ</span> {% else %} {{ order_item.get_total_item_price|intcomma }} đ {% endif %}
                            <a style="color: red;" href="{% url 'core:remove_from_cart' order_item.item.slug %}">
                                <i class="fas fa-trash float-right"></i>
                            </a>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="5">Giỏ hàng của bạn không có sản phẩm nào</td>
                    </tr>
                    <tr>
                        <td colspan="5">
                            <a href="/" class="btn btn-primary float-right">Tiếp tục mua sắm</a>
                        </td>
                    </tr>
                    {% endfor %} {% if object.coupon %}
                    <tr>
                        <td colspan="4"><b>Coupon</b></td>
                        <td><b>-{{ object.coupon.amount|intcomma }} đ</b></td>
                    </tr>
                    {% endif %} {% if object.get_total %}
                    <tr>
                        <td colspan="4"><b>Cần thanh toán</b></td>
                        <td><b>{{ object.get_total|intcomma }} đ</b></td>
                    </tr>
                    <tr>
                        <td colspan="5">
                            <a href="{% url 'core:checkout' %}" class="btn btn-warning float-right ml-2">Tiến hành đặt hàng</a>
                            <a href="/" class="btn btn-primary float-right">Tiếp tục mua sắm</a>
                        </td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>

        </div>
    </div>
</main>
<!--Main layout-->
{% endblock content %}

templates/request_refund.html
{% extends "base.html" %} {% load humanize %} {% load crispy_forms_tags %} {% load static %} {% block content %}
<!--Main layout-->
<main>
    <div class="container">

        <h2>Request Refund</h2>
        <form action="" method="POST">
            {% csrf_token %} {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</main>
<!--Main layout-->
{% endblock content %}